### ISSUE TITLE
word embeddings link

### ISSUE THREAD

**Issue by gari-marcos** [xingdi-eric-yuan/GATA-public#1]
Hello, I tried to download the word embeddings by executing the following command: ```wget "https://bit.ly/38gklt3" ``` and I found the following error: ```ERROR 400: The requested URI does not represent any resource on the server.. ``` I checked the link and I found it has double slash before the $ sign: 
```https://textworld.blob.core.windows.net//$web/datasets/crawl-300d-2M.vec.h5```. I removed it and it worked properly, so maybe you could check it and fix it?
Thank you!

**Comment by xingdi-eric-yuan** [comment]
Thanks @gari-marcos !
