### ISSUE TITLE
The level of games

### ISSUE THREAD

**Issue by YunqiuXu** [xingdi-eric-yuan/GATA-public#10]
Hi Xingdi,

Thanks for sharing the clear code. 
I'm a bit confused about the level of games. According to Table 1 game statistics, the max score for L1-4 is
|Level|S|
|----|----|
|1|4|
|2|5|
|3|3|
|4|11|

However, I found that the max score in https://aka.ms/twkg/rl.0.1.zip is

|Level|S|
|----|----|
|1|3|
|2|4|
|3|4|
|4|3|
|5|3|
|6|3|
|7|5|
|8|5|
|9|11|
|10|11|

Are the levels in https://aka.ms/twkg/rl.0.1.zip inconsistent with those in paper? Or is there anything wrong when I'm computing the max score:
```
obs, infos = env.reset()
max_score = infos['game'].max_score
```

**Comment by xingdi-eric-yuan** [comment]
Great question and sorry for the confusion. The levels in the paper correspond to level 3/7/5/9 in the rl.0.1.zip . The dataset we provide contains a wider range of game difficulties. I will update this into the README. Thanks for asking!

**Comment by YunqiuXu** [comment]
Got it, thanks for quick response
