### ISSUE TITLE
GATA-GTF rl training error

### ISSUE THREAD

**Issue by subhajitchaudhury** [xingdi-eric-yuan/GATA-public#14]
Hello, During GATA-GTF rl training with `train_rl_with_ground_truth_discrete_belief.py`, when trying to process line [1282](https://github.com/xingdi-eric-yuan/GATA-public/blob/b1d71c9b2f4477bae3e24b2eb895133bf7be9ac4/agent.py#L1282), I am getting an error on the np.stack due to `prev_graph_hidden_state` being a list of list of triplets with variable sizes. Any ideas what might be going wrong? Thanks.

For eg: `[len(x) for x in prev_graph_hidden_state]` gives `[39, 49, 49, 49, 35, 49, 48, 45, 39, 39, 45, 49, 42, 41, 43, 51, 51, 43, 46, 45, 48, 45, 41, 48, 45, 45, 40, 39, 41, 48, 45, 41, 39, 49, 49, 42, 42, 46, 35, 52, 41, 41, 46, 49, 45, 48, 48, 44, 43, 40, 40, 42, 42, 49, 42, 40, 42, 40, 40, 51, 41]` just before the np.stack command.

**Comment by xingdi-eric-yuan** [comment]
Hi @subhajitchaudhury , thanks for asking. This seems to be an overlook when we extract this repo from another development repo. A quick fix is to change  [THIS LINE](https://github.com/xingdi-eric-yuan/GATA-public/blob/master/configs/train_gata_gtf_rl.yaml#L52)  to be False. The same thing happens in GATA-GTP config as well. Thanks for reporting and we will fix this.

**Comment by xingdi-eric-yuan** [comment]
I have merged a PR that should have fixed this, please let me know if anything else you find weird. Thanks!

**Comment by subhajitchaudhury** [comment]
Thanks @xingdi-eric-yuan for the prompt action. The PR solved the issue and the rl training is now running. I am closing this issue.
