### ISSUE TITLE
License is missing?

### ISSUE THREAD

**Issue by tongzhoumu** [xingdi-eric-yuan/GATA-public#25]
Hi GATA authors,

It seems the codes use MIT license according to the README. However, the license file is missing. The [license link](https://github.com/xingdi-eric-yuan/GATA-public/blob/master/LICENSE) in README  does not work. Can you fix it? Thanks!

**Comment by xingdi-eric-yuan** [comment]
Thanks for pointing this out! I have updated the license file.
