### ISSUE TITLE
Filter "examine" and "look" commands

### ISSUE THREAD

**Issue by MathieuTuli** [xingdi-eric-yuan/GATA-public#26]
Hi authors,

I was wondering what the purpose of filtering the "examine" and "look" commands was (https://github.com/xingdi-eric-yuan/GATA-public/blob/1dc673ddfc08e7e2de2786665d6a24e7109c7888/train_rl_with_discrete_belief.py#L98-L101).

I couldn't find a reference to why in the paper nor in the code. Further, it seems to me like the agent is still able to perform these actions (which was confirmed by looking at some replays, where the agent performs the "examine cookbook"). 

Thanks for any insight.

**Comment by MarcCote** [comment]
We do allow the `examine cookbook`, but filter out the other 'examine' commands in addition to the `look` command.

The main reason is to simplify the learning problem as examining objects (except for the cookbook) are not needed to complete the cooking tasks. It is an oversaw on our part if this is not mentioned in the paper.

**Comment by MathieuTuli** [comment]
Thanks that clarifies things
