### ISSUE TITLE
Data link is not working

### ISSUE THREAD

**Issue by lyon424** [xingdi-eric-yuan/GATA-public#30]
Hello,
I was trying to download the data, in this step cd obs_gen.0.1 ; wget https://aka.ms/twkg/obs_gen.0.1.zip ; unzip obs_gen.0.1.zip ; cd ..
but it seems the link is not working. When I try going to the site itself it states <Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:79cca9c3-d01e-0043-4fe4-b15ef6000000 Time:2024-05-29T16:19:51.2374420Z</Message>
</Error>

**Comment by MarcCote** [comment]
Thanks for letting us know. I've uploaded the data on Github (see https://github.com/xingdi-eric-yuan/GATA-public/releases/tag/data). I also updated (https://github.com/xingdi-eric-yuan/GATA-public/commit/4a4132b5704fa6e788ef52afc2c21ca29f1965a8) all the links to point directly to the new uploads. Can you let us if that works for you?

**Comment by lyon424** [comment]
Hello, I was able to download the data using the update thank you! Another issues I saw was that 
the same issue occurs with # Download FastText Word Embeddings
curl -L -o crawl-300d-2M.vec.h5 "https://bit.ly/2U3Mde2" where it states that This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:6060a237-501e-0034-47f8-b1dbb7000000 Time:2024-05-29T18:47:14.3799842Z</Message>
</Error>

**Comment by MarcCote** [comment]
@lyon424 did you solve the issue with `crawl-300d-2M.vec.h5`?

**Comment by lyon424** [comment]
Hello, I originally thought I did as a file was created after doing wget in the repo, but looking back it doesn't seem like it worked. As when opening the file it has an error message.

**Comment by MarcCote** [comment]
Alright. I updated the link, you can try

    curl -L -o crawl-300d-2M.vec.h5 "https://github.com/xingdi-eric-yuan/GATA-public/releases/download/data/crawl-300d-2M.vec.h5"
