### ISSUE TITLE
textworld module not found when training

### ISSUE THREAD

**Issue by gari-marcos** [xingdi-eric-yuan/GATA-public#5]
Hello, I was training the agent and I found the following error:
```
Traceback (most recent call last):
  File "train_rl.py", line 425, in <module>
    train()
  File "train_rl.py", line 37, in train
    agent.batch_size)
  File "/home/gari/Documentos/TextWorld/git/GATA-public/reinforcement_learning_dataset.py", line 22, in get_training_game_env
    env_id = textworld.gym.make_batch(env_id, batch_size=batch_size, parallel=True)
AttributeError: module 'textworld.gym' has no attribute 'make_batch'
```
I checked the [TextWorld doc](https://textworld.readthedocs.io/en/stable/textworld.gym.html) and I found that module is no longer available, so I don't know how to deal with it.
Thank you in advance.

**Comment by MarcCote** [comment]
Thanks for pointing this out. TextWorld had a new release just after we released this code. See PR #6  for a fix.

**Comment by MarcCote** [comment]
@gari-marcos Since PR #6 doesn't have too many changes, you could simply make the change to your local code directly. Otherwise, the proper way to test a PR, is to git checkout the branch in question (https://github.com/xingdi-eric-yuan/GATA-public/tree/fix_remove_make_batch).

**Comment by gari-marcos** [comment]
Thanks, it works properly!
